### ISSUE TITLE
cmake 3.10 MPI CXX?

### ISSUE THREAD

**Issue by dylex** [TRIQS/mpi#3]
https://github.com/TRIQS/mpi/blob/a57df55009a8ca1278915028c33ed4662bbe0432/c%2B%2B/mpi/CMakeLists.txt#L51

```
CMake Error at /home/build/triqs/deps/mpi_src/c++/mpi/CMakeLists.txt:51 (target_compile_definition):
  Unknown CMake command "target_compile_definition".
```

I'm guessing this should be `target_compile_definitions` but with that I get:

```
CMake Error at deps/mpi/c++/mpi/CMakeLists.txt:51 (target_compile_definitions):
  target_compile_definitions may only be set INTERFACE properties on
  INTERFACE targets
```

FWIW, cmake 3.10.2's FindMPI seems to include `MPI_CXX_SKIP_MPICXX`.

**Comment by Wentzell** [comment]
@dylex Thanks for pointing this out!
