### ISSUE TITLE
Installation of triqs with mpich fails because of mpi

### ISSUE THREAD

**Issue by merkelm** [TRIQS/mpi#8]
### Description

Compiling the newest version (unstable branches triqs and mpi) of triqs with MPICH does not work for me anymore. I'm using the same dockerfile as last December, when it still worked.

### Steps to Reproduce

1. Following the procedure from triqs jenkins, I pasted together the [Dockerfile.ubuntu-gcc](https://github.com/TRIQS/triqs/blob/unstable/packaging/Dockerfile.ubuntu-gcc) and [Dockerfile.build](https://github.com/TRIQS/triqs/blob/unstable/Dockerfile.build) and then added a git clone command to the dockerfile to get triqs into the docker container. This compiles without problems (as expected by the successful checks by jenkins).
2. I then change from openMPI to MPICH and installing mpi4py through pip to link it to mpich, which leads to [this dockerfile](https://github.com/TRIQS/mpi/files/8131800/triqs_dockerfile_mpich.txt). Now the compilation stops with the error

```
[  7%] Linking CXX shared module copy_move_stat.cpython-38-x86_64-linux-gnu.so
In file included from /src/triqs/c++/triqs/utility/exceptions.hpp:23,
                 from /src/triqs/c++/triqs/atom_diag/impl/../atom_diag.hpp:26,
                 from /src/triqs/c++/triqs/atom_diag/impl/atom_diag.cpp:21:
/home/build/triqs/deps/mpi_src/c++/mpi/mpi.hpp: In member function 'void mpi::communicator::barrier(long int)':
/home/build/triqs/deps/mpi_src/c++/mpi/mpi.hpp:127:29: error: cannot convert 'std::nullptr_t' to 'MPI_Request' {aka 'int'} in initialization
  127 |           MPI_Request req = nullptr;
      |                             ^~~~~~~
```

Based on the error message, I'd guess that commit 25e6fe9b9c0c9bfadeed60667d725e439ec40e90 from Jan 25 causes the problem.

Thank you already for your help!
Cheers, Max

**Comment by Wentzell** [comment]
Thank you @merkelm for pointing this out! This should be fixed in https://github.com/TRIQS/mpi/commit/a85646398f3f5e21acab69629d409ea06d9e1d40. Reopen if needed!

**Comment by merkelm** [comment]
Thank you for your fast reply! The original problem is fixed but now the compilation fails with more similar errors. Grepping for "error" in the compilation output gives this result (duplicates removed):
```
/home/build/triqs/deps/mpi_src/c++/mpi/mpi.hpp:392:12: error: cannot convert 'std::nullptr_t' to 'MPI_Op' {aka 'int'} in initialization
/home/build/triqs/deps/mpi_src/c++/mpi/mpi.hpp:381:12: error: cannot convert 'std::nullptr_t' to 'MPI_Op' {aka 'int'} in initialization
/home/build/triqs/deps/mpi_src/c++/mpi/mpi.hpp:336:18: error: cannot convert 'std::nullptr_t' to 'MPI_Datatype' {aka 'int'} in initialization
```
Comparing with the code changes in the previously mentioned 25e6fe9b9c0c9bfadeed60667d725e439ec40e90, it seems like they correspond to all the lines introducing nullptr.

**Comment by Wentzell** [comment]
Dear @merkelm, I have now fixed also the other variable initializations. Please let me know if you have further problems!

**Comment by merkelm** [comment]
Thank you @Wentzell, everything compiles again now!
